### ISSUE TITLE
Definir efeitos sonoros

### ISSUE THREAD

**Issue by andreagami** [MothershipStudio/GGJ2017#18]
GUI
Trocando opções no menu;
Selecionando item no menu;

Special Effects
Caixa quebrando;
Onda magnética atraindo;
Onda magnética repelindo;
Carregando explosão sonora;
Explosão sonora (quebrando barreira do som).

Characters
Personagem sofrendo dano;
Personagem morrendo;
Caindo em abismo;
Destruindo inimigo (mais de uma versão).

Game Play Elements
Caindo sobre espetos;

Terrain (Environment)
Som de cidade futurista (carros voando, letreiros piscando, etc).

Motion
Andar sobre superfície de asfalto;
Correr sobre superfície de asfalto;
Andar sobre superfície metálica;
Correr sobre superfície metálica;
Pular sobre superfície de asfalto;
Pular sobre superfície metálica;

**Comment by SraQjo** [comment]
GUI
Trocando opções no menu- Concluido
Selecionando item no menu- Concluido

Special Effects
Caixa quebrando- Concluido
Onda magnética atraindo- Concluido
Onda magnética repelindo- Concluido
Carregando explosão sonora- Concluido
Explosão sonora (quebrando barreira do som)-  Concluido

Characters
Personagem sofrendo dano- Concluido
Personagem morrendo- Concluido
Caindo em abismo- Concluido
Destruindo inimigo (mais de uma versão)- Concluido

Game Play Elements
Caindo sobre espetos- Concluido

Motion
Andar sobre superfície de asfalto- Concluido
Correr sobre superfície de asfalto- Concluido
Andar sobre superfície metálica;
Correr sobre superfície metálica;
Pular sobre superfície de asfalto- Concluido
Pular sobre superfície metálica;

Terrain (Environment)
Som de cidade futurista (carros voando, letreiros piscando, etc)- Concluido
